[context.production.environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[context."staging".environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[context."master".environment]
  REACT_APP_CHAIN_ID = "5"
  REACT_APP_ENABLE_HISTORY = "true"

[context.deploy-preview.environment]
  REACT_APP_CHAIN_ID = "8080"
  REACT_APP_ENABLE_HISTORY = "true"

[functions]
  directory = "packages/vrbs-webapp/functions"

[build]
  command = "git submodule update --init --recursive --depth=1 && yarn workspace @vrbs/webapp build"
  publish = "packages/vrbs-webapp/build"
